image: openjdk:8-jdk

services:
 - name: mysql:latest
   alias: localhost

variables:
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: shortflix


stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew clean build

unitTests:
  stage: test
  script:
    - ./gradlew test
